services:
  postgres:
    image: postgres:16
    container_name: asset-postgres
    environment:
      POSTGRES_DB: assetdb
      POSTGRES_USER: assetuser
      POSTGRES_PASSWORD: assetpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
